FROM ubuntu:latest

WORKDIR /app
ADD helper helper
ADD config.yaml config.yaml

RUN apt update \
  && apt-get install -y \
  curl \
  unzip \
  wget \
  gnupg2 \
  xz-utils \
  tar \
  libatk1.0-0 \
  libatk-bridge2.0-0 \
  libcups2 \
  libxkbcommon-x11-0 \
  libxdamage1 \
  libgbm-dev \
  libpangocairo-1.0-0 \
  libnss3-dev \
  libxcomposite1 \
  libxfixes3 \
  libxrandr2 \
  libasound2t64

# Install google
RUN curl -L -O https://github.com/adryfish/fingerprint-chromium/releases/download/136.0.7103.113/ungoogled-chromium_136.0.7103.113-1_linux.tar.xz
RUN xz -dk ungoogled-chromium_136.0.7103.113-1_linux.tar.xz
RUN tar -xvf ungoogled-chromium_136.0.7103.113-1_linux.tar
RUN mv ungoogled-chromium_136.0.7103.113-1_linux chromium
RUN ln -s /app/chromium/chrome /bin/chromium

RUN chmod +x helper \
  && chmod -R 777 /app
  #&& mkdir log && chmod 777 log \
  #&& mkdir tmp && chmod 777 tmp

ENV ARG "--port 7860"
CMD ["./helper ${ARG}"]
ENTRYPOINT ["sh", "-c"]
