port: 7860
timeout: 300
ja3: 771,4865-4866-4867-49195-49199-49196-49200-52393-52392-49171-49172-156-157-47-53,0-23-65281-10-11-35-16-5-13-18-51-45-43-27-17513-21,29-23-24,0
mappers:
  - addr: https://ai.baidu.com
    routes:
      - path: ^/baidu/*
        rewrite: /$1
  - addr: http://127.0.0.1:7379
    routes:
      - path: ^/webdis/*
        rewrite: /$1
  - addr: http://127.0.0.1:3000
    routes:
      - path: ^/laf/*
        rewrite: /$1
  - addr: https://freegpt35-brown.vercel.app
    routes:
      - path: ^/oai/wapi/*
        rewrite: /$1
  - addr: http://127.0.0.1:3002
    routes:
      - path: ^/firecrawl/*
        rewrite: /$1
  - addr: http://127.0.0.1:5010
    routes:
      - path: ^/ppl/*
        rewrite: /$1